// Code generated by "stringer -type=ClientKind -linecomment"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClientUnknown-0]
	_ = x[ClientPuppet-1]
	_ = x[ClientAdmin-2]
}

const _ClientKind_name = "unknownpuppetadmin"

var _ClientKind_index = [...]uint8{0, 7, 13, 18}

func (i ClientKind) String() string {
	if i < 0 || i >= ClientKind(len(_ClientKind_index)-1) {
		return "ClientKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClientKind_name[_ClientKind_index[i]:_ClientKind_index[i+1]]
}
